services:
    keycloak:
        image: quay.io/keycloak/keycloak:24.0.0
        hostname: keycloak
        container_name: keycloak
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: password
        ports:
            - "8180:8080"
        volumes:
            - ./keycloak/imports:/opt/keycloak/data/import
        command: 
            - start-dev
            - --import-realm
        networks:
            - default
networks:
    default:
